# Generated by Django 6.1.1 on 2026-09-09 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=100)),
                ('site_size', models.CharField(max_length=50)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('sqft', models.CharField(blank=True, max_length=50, null=True)),
                ('access', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('dom', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_comments', models.TextField(blank=True, null=True)),
                ('updated_dom', models.IntegerField(blank=True, null=True)),
                ('updated_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
    ]
