# Generated by Django 6.1.1 on 2026-09-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_access_id_property_analysis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='apprname',
            new_name='appraiser_name',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='improv',
            new_name='improvements',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='insp',
            new_name='inspected_by',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='insp_date',
            new_name='inspected_date',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='site_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='veri_by',
            new_name='verified_by',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='veri_date',
            new_name='verified_date',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='veri_to',
            new_name='verified_to',
        ),
    ]
