# Generated by Django 6.1.1 on 2026-09-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_apprname_property_appraiser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
