# Generated by Django 6.1.1 on 2026-09-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
